# Generated by Django 5.2.4 on 2025-09-30 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('curso_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('duracao', models.DurationField()),
            ],
            options={
                'db_table': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('disciplina_id', models.AutoField(primary_key=True, serialize=False)),
                ('materia', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'Disciplina',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('matricula_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_ingresso', models.DateField(auto_now_add=True)),
                ('status_matricula', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Matricula',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('turma_id', models.AutoField(primary_key=True, serialize=False)),
                ('dias_semana', models.CharField(max_length=50)),
                ('horarios', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('duracao', models.DurationField()),
                ('tipo', models.CharField(choices=[('presencial', 'Presencial'), ('semi', 'Semi-presencial'), ('ead', 'EAD')], max_length=10)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Turma',
            },
        ),
        migrations.CreateModel(
            name='GradeCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.disciplina')),
            ],
            options={
                'db_table': 'GradeCurricular',
            },
        ),
    ]
