# Generated by Django 5.2.6 on 2025-11-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlocacaoProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Alocação de Professor',
                'verbose_name_plural': 'Alocações de Professores',
                'db_table': 'Cursos_alocacaoprofessor',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Sem Nome', max_length=150, unique=True, verbose_name='Nome do Curso')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('carga_horaria', models.PositiveIntegerField(default=40, verbose_name='Carga Horária (h)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Sem Nome', max_length=150, verbose_name='Nome da Disciplina')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('carga_horaria', models.PositiveIntegerField(default=40, verbose_name='Carga Horária (h)')),
            ],
        ),
        migrations.CreateModel(
            name='GradeCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'GradeCurricular',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('matricula_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_ingresso', models.DateField(auto_now_add=True)),
                ('status_matricula', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Matricula',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('turma_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('dias_semana', models.CharField(max_length=50)),
                ('entrada_horas', models.CharField(blank=True, max_length=100, null=True)),
                ('saida_horas', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('presencial', 'Presencial'), ('semi', 'Semi-presencial'), ('ead', 'EAD')], max_length=10)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Turma',
            },
        ),
    ]
