# Generated by Django 5.2.8 on 2025-11-17 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cursos', '0001_initial'),
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaoprofessor',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.professor'),
        ),
        migrations.AddField(
            model_name='alocacaoprofessor',
            name='Curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.curso'),
        ),
        migrations.AddField(
            model_name='gradecurricular',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.curso'),
        ),
        migrations.AddField(
            model_name='gradecurricular',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.disciplina'),
        ),
        migrations.AddField(
            model_name='curso',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='cursos', through='Cursos.GradeCurricular', to='Cursos.disciplina'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.aluno'),
        ),
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.curso'),
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Login.professor'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.turma'),
        ),
        migrations.AlterUniqueTogether(
            name='gradecurricular',
            unique_together={('curso', 'disciplina')},
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('aluno', 'turma')},
        ),
    ]
