# Generated by Django 5.2.6 on 2025-11-27 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaoprofessor',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.professor'),
        ),
        migrations.AddField(
            model_name='alocacaoprofessor',
            name='Curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='gradecurricular',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='gradecurricular',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.disciplina'),
        ),
        migrations.AddField(
            model_name='curso',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='cursos', through='cursos.GradeCurricular', to='cursos.disciplina'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.aluno'),
        ),
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.professor'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.turma'),
        ),
        migrations.AlterUniqueTogether(
            name='gradecurricular',
            unique_together={('curso', 'disciplina')},
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('aluno', 'turma')},
        ),
    ]
