# Generated by Django 5.2.6 on 2025-10-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
