# Generated by Django 5.2.4 on 2025-10-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='duracao',
            field=models.IntegerField(),
        ),
    ]
