# Generated by Django 5.2.7 on 2025-10-10 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='Cursos.curso'),
        ),
    ]
