# Generated by Django 5.2.7 on 2025-11-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0003_alter_turma_duracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='duracao',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='horarios',
        ),
        migrations.AddField(
            model_name='turma',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='entrada_horas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='saida_horas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
