# Generated by Django 5.2.7 on 2025-10-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0003_disciplina_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='disciplina',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='curso',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='Cursos.disciplina'),
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='curso',
        ),
    ]
