# Generated by Django 5.2.6 on 2025-11-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('atividade_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo_material', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('docx', 'DOCX'), ('imagem', 'Imagem'), ('outro', 'Outro')], max_length=10, null=True)),
                ('url_material', models.URLField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='atividades_files/')),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='AtividadeEntregue',
            fields=[
                ('atividade_entregue_id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField(blank=True, null=True)),
                ('tipo_arquivo', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('docx', 'DOCX'), ('imagem', 'Imagem'), ('outro', 'Outro')], max_length=10, null=True)),
                ('url_arquivo', models.URLField(blank=True, null=True)),
                ('data_entrega', models.DateTimeField(auto_now_add=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'AtividadesEntregues',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('avaliacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_limite_entrega', models.DateTimeField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='avaliacoes_anexos/')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'db_table': 'Avaliacao',
            },
        ),
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('tipo_atividade_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(choices=[('FIXACAO', 'Fixação'), ('AVALIACAO', 'Avaliações'), ('RELATORIO', 'Relatórios')], max_length=50, unique=True)),
                ('cor', models.CharField(help_text='Cor em formato hexadecimal para o card.', max_length=7)),
                ('icone', models.CharField(help_text="Classe do ícone (ex: 'fas fa-check-square').", max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Atividade',
                'verbose_name_plural': 'Tipos de Atividades',
                'db_table': 'TiposAtividades',
            },
        ),
    ]
