# Generated by Django 5.2.4 on 2025-09-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('atividade_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo_material', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('docx', 'DOCX'), ('imagem', 'Imagem'), ('outro', 'Outro')], max_length=10, null=True)),
                ('url_material', models.URLField(blank=True, null=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='AtividadeEntregue',
            fields=[
                ('atividade_entregue_id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField(blank=True, null=True)),
                ('tipo_arquivo', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('docx', 'DOCX'), ('imagem', 'Imagem'), ('outro', 'Outro')], max_length=10, null=True)),
                ('url_arquivo', models.URLField(blank=True, null=True)),
                ('data_entrega', models.DateTimeField(auto_now_add=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'AtividadesEntregues',
            },
        ),
    ]
