<<<<<<< HEAD:ProjetoGC/atividades/migrations/0002_initial.py
# Generated by Django 5.2.6 on 2025-10-14 17:48
=======
# Generated by Django 5.2.7 on 2025-10-09 19:08
>>>>>>> origin/secretaria:ProjetoGC/Atividades/migrations/0002_initial.py

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Atividades', '0001_initial'),
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.turma'),
        ),
        migrations.AddField(
            model_name='atividadeentregue',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atividades.atividade'),
        ),
        migrations.AddField(
            model_name='atividadeentregue',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.matricula'),
        ),
        migrations.AlterUniqueTogether(
            name='atividadeentregue',
            unique_together={('atividade', 'matricula')},
        ),
    ]
