# Generated by Django 5.2.6 on 2025-11-27 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividades', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.turma'),
        ),
        migrations.AddField(
            model_name='atividadeentregue',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividades.atividade'),
        ),
        migrations.AddField(
            model_name='atividadeentregue',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.matricula'),
        ),
    ]
