# Generated by Django 5.2.6 on 2025-10-31 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('tipo_atividade_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(choices=[('FIXACAO', 'Fixação'), ('AVALIACAO', 'Avaliações'), ('RELATORIO', 'Relatórios')], max_length=50, unique=True)),
                ('cor', models.CharField(help_text='Cor em formato hexadecimal para o card.', max_length=7)),
                ('icone', models.CharField(help_text="Classe do ícone (ex: 'fas fa-check-square').", max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Atividade',
                'verbose_name_plural': 'Tipos de Atividades',
                'db_table': 'TiposAtividades',
            },
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Atividades.tipoatividade'),
        ),
    ]
