# Generated by Django 5.2.6 on 2025-11-27 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividades', '0002_initial'),
        ('cursos', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.professor'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.turma'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atividades.tipoatividade'),
        ),
        migrations.AlterUniqueTogether(
            name='atividadeentregue',
            unique_together={('atividade', 'matricula')},
        ),
    ]
