# Generated by Django 5.2.6 on 2025-11-17 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Atividades', '0002_initial'),
        ('Cursos', '0001_initial'),
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.professor'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.turma'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Atividades.tipoatividade'),
        ),
        migrations.AlterUniqueTogether(
            name='atividadeentregue',
            unique_together={('atividade', 'matricula')},
        ),
    ]
