# Generated by Django 5.2.6 on 2025-11-07 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0003_tipoatividade_atividade_tipo'),
        ('Cursos', '0003_alter_turma_duracao'),
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('avaliacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_limite_entrega', models.DateTimeField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='avaliacoes_anexos/')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.turma')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'db_table': 'Avaliacoes',
            },
        ),
    ]
