# Generated by Django 5.2.7 on 2025-11-16 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cursos', '0001_initial'),
        ('Login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('solicitacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('declaracao', 'Declaração'), ('realocacao', 'Realocação'), ('trancamento', 'Trancamento')], max_length=15)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('negado', 'Negado')], default='pendente', max_length=20)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.secretaria')),
                ('turma_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_destino', to='Cursos.turma')),
                ('turma_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_origem', to='Cursos.turma')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Solicitacao',
            },
        ),
    ]
