# Generated by Django 5.2.4 on 2025-10-16 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0003_alter_turma_duracao'),
        ('Solicitacao', '0002_alter_solicitacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='turma_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_destino', to='Cursos.turma'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='turma_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_origem', to='Cursos.turma'),
        ),
    ]
