# Generated by Django 5.2.6 on 2025-09-29 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('solicitacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('declaracao', 'Declaração'), ('realocacao', 'Realocação'), ('trancamento', 'Trancamento')], max_length=15)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído')], default='pendente', max_length=20)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.secretaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Solicitacao',
            },
        ),
    ]
