# Generated by Django 5.2.6 on 2025-11-27 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('aula_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('presencial', 'Presencial'), ('ead', 'EAD')], max_length=10)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.turma')),
            ],
            options={
                'db_table': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('frequencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('presenca', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.aula')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.matricula')),
            ],
            options={
                'db_table': 'Frequencia',
                'unique_together': {('aula', 'matricula')},
            },
        ),
    ]
