# Generated by Django 5.2.4 on 2025-11-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
