# Generated by Django 5.2.8 on 2025-11-17 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Calendario', '0001_initial'),
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='Cursos.turma'),
        ),
    ]
