# Generated by Django 5.2.8 on 2025-11-11 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0002_initial'),
        ('Calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='atividade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='Atividades.atividade'),
        ),
    ]
