# Generated by Django 5.2.8 on 2025-11-12 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0002_initial'),
        ('Calendario', '0002_evento_atividade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='criado_por',
        ),
        migrations.AlterField(
            model_name='evento',
            name='atividade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Atividades.atividade'),
        ),
    ]
