# Generated by Django 5.2.7 on 2025-10-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='data_ingresso',
        ),
    ]
