# Generated by Django 5.2.6 on 2025-10-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_usuario_options_usuario_nome_usuario_sobrenome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
