# Generated by Django 5.2.6 on 2025-10-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_professor_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
